### PR TITLE
Fixing some frontend issues.

### PR DESCRIPTION
**Pull request by partha7978**
Still. the height issue is there. I'll fix this issue.

### CODE REVIEW

**Comment by partha7978** [comment]
Issue fixed. Kindly review it.

**Comment by d-shaktiranjan** [comment]
> Issue fixed. Kindly review it.

Thanks for your contribution.
After completion @rahul-choudhury  will review then I'll merge.
So kindly inform when this issues will completely resolved.

**Comment by rahul-choudhury** [comment]
looks good 👍

**Comment by d-shaktiranjan** [comment]
Hey @partha7978 , since we are using yarn in this project so package-lock.json is unnecessary & you are dealing with CSS files only so yarn.lock should not be modified.
So kindly request to you please remove package-lock.json & restore yarn.lock file in your next commit or the final commit.
Thanks

**Comment by partha7978** [comment]
All margin and width issues have been solved.

**Comment by partha7978** [comment]
I removed the package-lock.json and restored the yarn.lock as per your instruction.

**Comment by partha7978** [comment]
Hey @d-shaktiranjan, I tried to fix the width issue on the large screen. you can check and tell me whether it's fixed or not!!

**Review by rahul-choudhury — COMMENTED** [review]
👍

**Comment by d-shaktiranjan** [comment]
Thanks @partha7978 for your contribution.
😊

**Pull request merged**
